@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "Клиент")
System_Ext(mainframe_system, "Основная система банка", $descr="Хранит всю основную банковскую информацию о клиентах, счетах, транзакциях, тарифах и т.п.")
System_Ext(email_system, "Внешний почтовый сервис", $descr="")

System_Boundary(c1, "Онлайн Банк", $link="https://github.com/plantuml-stdlib/C4-PlantUML") {
    Container(web_app, "Веб приложение", $descr="Предоставляет статичный контент для SPA.", $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md")
    Container(spa, "SPA", $descr="Предоставляет клиентам онлайн функционал с помощью веб браузера.", $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md")
    Container(mobile_app, "Mobile App", $descr="Предоставляет клиентам функционал с помощью мобильных устройств.", $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md")
    Container(api, "API Приложение", $descr="Предоставляет банковский функционал с помощью JSON/HTTPS API.", "Java and Spring MVC", $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md")
    ContainerDb(db, "База данных", "Реляционная база данных", $descr="Хранит регистрационную информацию, хешированные учетные данные аутентификации, логи и т.п.", $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md")
}

Rel(user, spa, "Просматривает баланс счетов и совершает платежи с помощью", "HTTPS")
Rel(user, mobile_app, "Просматривает баланс счетов и совершает платежи с помощью", "HTTPS")
Rel(email_system, user, "Отправляет email")
Rel(web_app, spa, "Контент")
Rel(spa, api, "Вызовы API", "JSON/HTTPS")
Rel(mobile_app, api, "Вызовы API", "JSON/HTTPS")
Rel(api, mainframe_system, "Вызовы API", "XML/HTTPS")
Rel(api, email_system, "Отправка email", "SMTP")
Rel(api, db, "Чтение и запись", "JDBC")
@enduml