@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Container(web_app, "Веб приложение", $descr="Предоставляет статичный контент для SPA.", $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md")
Container(spa, "SPA", $descr="Предоставляет клиентам онлайн функционал с помощью веб браузера.", $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md")

System_Boundary(api, "API Приложение", $link="https://github.com/plantuml-stdlib/C4-PlantUML/blob/master/LayoutOptions.md") {
}

@enduml