@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "Клиент")
System_Boundary(c1, "Онлайн Банк") {
    Container(web_app, "Веб приложение")
}

Rel(user, c1, "Просматривает баланс счетов и совершает платежи используя", "HTTPS")
@enduml